"""add_role_id_to_users

Revision ID: 0012a1fffe0c
Revises: f0a6220c1884
Create Date: 2026-06-15 17:15:08.320338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0012a1fffe0c'
down_revision: Union[str, Sequence[str], None] = 'f0a6220c1884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
