"""Add case management schema

Revision ID: 540975c03d80
Revises: 9c54243281ad
Create Date: 2026-06-06 18:25:20.984874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540975c03d80'
down_revision: Union[str, Sequence[str], None] = '9c54243281ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('analyst', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['risk_assessments.assessment_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_alert_id'), 'cases', ['alert_id'], unique=True)
    op.create_index(op.f('ix_cases_analyst'), 'cases', ['analyst'], unique=False)
    op.create_table('analyst_notes',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_analyst_notes_case_id'), 'analyst_notes', ['case_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_timeline_events_case_id'), 'timeline_events', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_case_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_analyst_notes_case_id'), table_name='analyst_notes')
    op.drop_table('analyst_notes')
    op.drop_index(op.f('ix_cases_analyst'), table_name='cases')
    op.drop_index(op.f('ix_cases_alert_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
